name: RCHoppersPluginChunkHopper
version: 0.1-SNAPSHOT
author: Lolimi

depend: [RCHoppers, Vault]
softdepend: [ShopGUIPlus]
loadbefore: [RCHoppers, ShopGUIPlus, Vault, BentoBox]

main: io.github.lolimi.rchoppers.plugins.main.Main

api-version: 1.13

commands:
   gch:
   gu: 
   
   
permissions:
   chunkhoppers.admin:
      description: for gch and gu commands
      default: op